### ISSUE TITLE
Plugin enabled but not installed

### ISSUE THREAD

**Issue by reetik-raj** [portothree/kong-custom-auth#1]
I cloned this plugin in the mentioned directory and added this to the plugins directive in kong.conf. But running my kong instance gives me the following error - 
`2021/06/29 09:14:01 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:502: error loading plugin schemas: on plugin 'custom-auth': 
custom-auth plugin is enabled but not installed;
no plugin found
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/init.lua:502: in function 'init'
        init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:502: error loading plugin schemas: on plugin 'custom-auth': custom-auth plugin is enabled but not installed;
no plugin found
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/init.lua:502: in function 'init'
        init_by_lua:3: in main chunk`
        Any help or suggestions would be highly appreciated.

**Comment by portothree** [comment]
Hi @reetik-raj,

What is the Kong version you are running?

Can you try changing your `lua_package_path` option to `/data/?.lua;;` and running it again?
Note: you can also set it with the env var `KONG_LUA_PACKAGE_PATH`
